[project]
name = "hornsim"
version = "0.1.0"
description = "A python implementation of the MMM toolbox by Bjørn Kolbrek."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.5.1",
    "pytest>=9.1.1",
    "scipy>=1.18.0",
]
license = "GPL-2.0-or-later"
license-files = ["LICENSE.txt"]

[build-system]
requires = ["setuptools>=77.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["hornsim*"]
